
name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "images/diagram.svg"
          excluded_paths: "ignore,.github,dist,node_modules"
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: "my-diagram"
          path: "downloads"
      
